version: '3.8'

services:
  squeeze:
    build:
      context: .
      dockerfile: Dockerfile  # This should point directly to Dockerfile in the main directory
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=Squeeze;User=ga-app;Password=ga-5ecret-%;TreatTinyAsBoolean=true;
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose NGINX on port 80 to handle traffic for the entire application
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - squeeze

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'Squeeze'
      MYSQL_USER: 'ga-app'
      MYSQL_PASSWORD: 'ga-5ecret-%'
      MYSQL_ROOT_PASSWORD: 'Ismail3012@'
    ports:
      - "3307:3306"

volumes:
  db-data:
